version: "2"
services:
  database:
    container_name : mongo-dev
    image: mongo
  twilio_datastore:
    container_name : mongo_express
    build: .
    ports:
      - "3002:3002"
    links:
      - database # link this service to the database service
    depends_on:
      - database
