version: "2"
services:
  twilio_datastore:
    build: .
    ports:
      - "3002:3002"
    links:
      - database # link this service to the database service
    depends_on:
      - database
  database:
    image: mongo
